### ISSUE TITLE
add doc comments to aqua dht into aqua file

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/registry#32]
- please clarify meaning of each parameters
- please clarify how secure/secured each parameters
- please clarify parameter placement weight/priority

**Comment by dzmitry-lahoda** [comment]
ok, docs are here https://doc.fluence.dev/aqua-book/libraries/aqua-dht , but if these will be in aqua files and generated would be easy to trust dht as some kind of storage

**Comment by folex** [comment]
(dht.aqua)[https://github.com/fluencelabs/aqua-dht/blob/9a72961/aqua/dht.aqua] is generated from WASM file, and WASM doesn't preserve comments from Rust, unfortunately. 

We have that feature planned.
