### ISSUE TITLE
How to approach DHT keys scoping and avoid collisions?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/registry#69]
1. register key1 by peerid1
2. register key1 by peerid2
3. step 2 fails
expected: peerid2 can propagate key1 from peerid1 retaining same security setting via propagate_key. why? if tenant has his own dht keys, it still wants to allow other to replicate tenant_keys to other nodes. it allows to maintain replication of key by other nodes who are interested in this key. may be add replicated parameter to allow to distinguish keys if desired. but because keys are signed, so replica will be same as original. may be limit replicas to be immutable (can be updated only via propagate values).

**Comment by alari** [comment]
Keynames are expected to be _scoped_ by a peer_id to provide the basic security guarantees. Otherwise, we have split-brain conflicts.

I doubt we could have a secure KV store with arbitrary keys without a blockchain. There are systems like ENS, handshake to solve this.

Anyway, I'm not sure I get the scenario from step 3 and whether it will be broken when we add signatures and address DHT by hashes instead of keys, or not. Ready to discuss it.

**Comment by dzmitry-lahoda** [comment]
oh, need to read whitepapers of ENS; but imagine we have ENS, would that allow some peer to take some DHT key in fluence? what is reference of ENS and handshakes?

**Comment by dzmitry-lahoda** [comment]
i do not want generic key, i want derived key. so it could be that SecuredDHT keys can be only keys derived by any means from public keys. 

1. Alice has private key K and its public part P.
2. Alice derives P' from K and produces signature of P' by K as S.
3. SecuredDHT can have only keys which are P' and has S.

**Comment by dzmitry-lahoda** [comment]
similar but not exactly to https://docs.solana.com/developing/programming-model/calling-between-programs#program-derived-addresses

(no exactly as it about producing  pubkeys with no private counter parts, but idea is similaar)

**Comment by dzmitry-lahoda** [comment]
or should we just have solana as best posible DNS provider build in? :)

**Comment by dzmitry-lahoda** [comment]
like IPFS is cohosted, may be host some blockchain which will form consensus under nodes (may be host parachain of subsrate?)

**Comment by dzmitry-lahoda** [comment]
there should be solution, or i do not see how to secure system

**Comment by dzmitry-lahoda** [comment]
so I do not need name, but secured address at least. name is needed, as it seems, only for root topics, so it will be NamedSecuredDHT

**Comment by folex** [comment]
> i do not want generic key, i want derived key. so it could be that SecuredDHT keys can be only keys derived by any means from public keys.
> 
> 1. Alice has private key K and its public part P.
> 2. Alice derives P' from K and produces signature of P' by K as S.
> 3. SecuredDHT can have only keys which are P' and has S.

We have plans to have keys scoped by public key this way. But it's not implemented yet.

However, you can start deriving DHT keys that way right now. There will be no colissions. And you already have a guarantee that no one but creator could take the ownership of a key. 

The only thing that'd missing is the check of the key validity by AquaDHT. You can assume it's already there, and then integrate when we implement this feature.

**Comment by dzmitry-lahoda** [comment]
sure,  i already use only keys for dht keys. i am not sure if possible to derived from libp2p keys for ed25519

https://www.google.com/search?q=ed25519+key+derivation&client=firefox-b-d&sxsrf=AOaemvKNTaKuXBMCKUQ6wodiodhx8GpAmg%3A1635756147571&ei=c6h_Yab-IciTlwTa6LfoDA&oq=ed25519+deriva&gs_lcp=Cgdnd3Mtd2l6EAMYADIGCAAQFhAeMgYIABAWEB46BAgAEEM6BQgAEIAEOgUIABCRAkoECEEYAVCpK1jvOGDBQGgCcAB4AIABpQGIAccHkgEDMS43mAEAoAECoAEBwAEB&sclient=gws-wiz

in rust it is not covered well may be, ts is worse. so need  https://github.com/libp2p/specs/blob/master/peer-ids/peer-ids.md

**Comment by dzmitry-lahoda** [comment]
so i will stick for using keys, not derived, as soon as there will be other key in fluence peer supported - than will check topic again. 

also I want to be able to do key stuff in wasm, so need to choose wasm compatible something, but i have troubles with version of everything https://github.com/fluencelabs/fluence/issues/1197 ...
