### ISSUE TITLE
remove `key.timestamp_created < timestamp_created` to make method idempotent

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/registry#72]
```
fn update_key(connection: &Connection, key: String, peer_id: String, timestamp_created: u64, timestamp_accessed: u64, pin: bool, weight: u32) -> SqliteResult<()> {
    let old_key = get_key_metadata_helper(&connection, key.clone(), timestamp_accessed);
    let pinned = pin as i32;
    let update_allowed = {
        match old_key {
            Ok(key) => key.peer_id == peer_id && key.timestamp_created < timestamp_created,
            Err(_) => true,
        }
    };
```

or return specific error code to detect the case of ` key.timestamp_created == timestamp_created`, so I can ignore this as not error

**Comment by justprosh** [comment]
This method is not throws an error of timestamp is outdated, it just skips the update. It returns error only if key exists with different peer id

**Comment by dzmitry-lahoda** [comment]
i doubt you are right... i am blocked.

**Comment by folex** [comment]
@dzmitry-lahoda can you please explain: 
- what you're doing (what's your intention)
- what do you expect
- what do you get instead
- provide the Aqua calls that you use

**Comment by justprosh** [comment]
Sorry, i look closer and see that it actually throws an error if key is outdated. I think we can ignore this as not an error

**Comment by alari** [comment]
Seems like it should be `key.timestamp_created <= timestamp_created`?

**Comment by dzmitry-lahoda** [comment]
it should be `key.timestamp_created  <= timestamp_created + SLA_MAXIMAL_TIME_SKEW_IN_SUBNETWORK`

**Comment by dzmitry-lahoda** [comment]
and it should diff data, if diff = 0 -> no error regardless for time. AND it should return different error for the case of old value applied.

and it still will not be good algorithm (there are options), so simplest case is to relax requirement, may be remove for now.

**Comment by dzmitry-lahoda** [comment]
cc @aburkut
